### ISSUE TITLE
热加载会出现错误

### ISSUE THREAD

**Issue by Yowi** [XyyF/vuex-register-module-demo#1]
可以在注销模块函数加上 module.hot 判断当前是否出于热加载中如：

```
    function unregisterModule(moduleName) {
      if (!module.hot) {
        store.unregisterModule(moduleName);
        // 清除moduleName
        const idx = moduleNames.indexOf(moduleName);
        moduleNames.splice(idx, 1);
      }
    }
```

**Comment by XyyF** [comment]
> 可以在注销模块函数加上 module.hot 判断当前是否出于热加载中如：
> 
> ```
>     function unregisterModule(moduleName) {
>       if (!module.hot) {
>         store.unregisterModule(moduleName);
>         // 清除moduleName
>         const idx = moduleNames.indexOf(moduleName);
>         moduleNames.splice(idx, 1);
>       }
>     }
> ```

您好，关于热重载的问题，我今天详细查看了，我梳理了以下思路：
1. 热更新的思路是，先挂载新组件，再移除旧组件，这就导致了热更新后，注册的module始终都是会被注销的
2. module.hot 是只要在webpack中注册了热更新插件，这是一个常驻的对象，如果在开发环境进行注销拦截的话，那么开发环境 和 生产环境 行为不一致，总归是存在问题的
3. 根据1的思路，这个问题的本质我觉得是，同一组件同时在页面中多次渲染，目前的方案没有很好的兼容这个场景，因为在我的设想中，注册模块的行为总是会发生在业务模块的根组件中，没有考虑到热更新时，同时存在两个组件
4. 我这边更新了方案，添加了一个类似计数的流程，你可以看看是否满足你的需求
